from typing import Any


class Log:
    def info(self, *args: Any) -> None: ...
    def warning(self, *args: Any) -> None: ...
    def error(self, *args: Any) -> None: ...
    def critical(self, *args: Any) -> None: ...
    def fatal(self, *args: Any) -> None: ...
    def debug(self, *args: Any) -> None: ...
